### PR TITLE
supported set the proxy from a configuration file

### PR DESCRIPTION
**Pull request by decker502**
I have tested it in ubuntu15.04 for Socks5 proxy.
### configuration file format:

```
[Proxy]
ProxyType=1
ProxyHostName=ip
ProxyPort=port
ProxyUserName=
ProxyPassword=
```
### ProxyType options:

```
Constant    Value   Description
QNetworkProxy::NoProxy     2    No proxying is used
QNetworkProxy::DefaultProxy    0    Proxy is determined based on the application proxy set using setApplicationProxy()
QNetworkProxy::Socks5Proxy     1    Socks5 proxying is used
QNetworkProxy::HttpProxy       3    HTTP transparent proxying is used
QNetworkProxy::HttpCachingProxy    4    Proxying for HTTP requests only
QNetworkProxy::FtpCachingProxy     5    Proxying for FTP requests only

```

### CODE REVIEW

**Comment by smarx** [comment]
_Automated message from Dropbox CLA bot_

@decker502, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/) and update the thread so we can consider merging your code.

**Comment by decker502** [comment]
Sorry, I have done it.

**Comment by timabbott** [comment]
@decker502 why did you close this PR?

**Comment by decker502** [comment]
@timabbott I had find a bug to be fixed.

**Pull request closed without merging**
