### PR TITLE
Better looking numbers for the notification icon

### PR DESCRIPTION
**Pull request by slurdge**
I tried to improve the look of the numbers in case of unread message.
I arrived at something that I think is nicer, both on Linux (tested with Mint) and Windows.

Please tell me what you think of it.

### CODE REVIEW

**Comment by smarx** [comment]
_Automated message from Dropbox CLA bot_

@slurdge, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by lfranchi** [comment]
Thanks @slurdge! Can you include a couple of screenshots? It'll help me review faster :)

p.s. sorry for the delay -- was on 2 weeks of vacation. Back now!

**Comment by slurdge** [comment]
@lfranchi Yeah I'll do that shortly.

**Comment by lfranchi** [comment]
@slurdge ping in case you are interested :)

**Comment by slurdge** [comment]
@lfranchi yeah sorry got busy and kinda forgot it.
Anyway here are some screenshots.

zulip-linux-3
zulip-linux-99
zulip-linux-inf
zulip-win-3
zulip-win-99
zulip-win-inf

**Comment by slurdge** [comment]
I think the next step would be to include a special font, but we would need:
- A font with appropriate characteristics and license;
- A way to embed it into the application

Both are a little bit difficult IMHO, so we could roll with this as a temporary improvement.

**Comment by lfranchi** [comment]
Thanks! There are some whitespace issues with the diff -- if you can fix those i'll be happy to merge :)

**Comment by lfranchi** [comment]
Quick ping on this! If you can fix up the whitespace issues (some of the lines you added have the incorrect indentation) I'll go ahead and merge this!

**Comment by slurdge** [comment]
Sorry for the lack of update, i'm in the middle of moving across the world. Thank for the ping, changed to spaces so it should be ok i guess.

**Comment by lfranchi** [comment]
Thanks! Merged :)

**Pull request merged**
